# This is a basic workflow to help you get started with Actions

name: A1

# Controls when the workflow will run
on: push
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: step Print my_testing
        run: echo "my_testing"

      - name: step Branch-name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: step Checkout-code
        uses: actions/checkout@v3

      - name: step Set up Java
        uses: actions/setup-java@v3

        with:
          distribution: 'adopt'
          java-version: '17'

# Warning:  The property 'sonar.login' is deprecated and will be removed in the future. Please use the 'sonar.token' property instead when passing a token.
      - name: analysis.author
        run: echo ${{ github.actor }}
        
      - name: SonarQube Scan

        # run: |
        #   BRANCH_NAME=${GITHUB_REF##*/}
        #   SONAR_PROJECT_KEY="project-${BRANCH_NAME//\//-}"
        #   mvn sonar:sonar -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.host.url=http://31.220.85.178:9001 -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.analysis.author=${{ github.actor }}

        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          SONAR_PROJECT_KEY="project-${BRANCH_NAME//\//-}"
          SONAR_PROJECT_NAME="Project ${BRANCH_NAME}"

      - name: BRANCH_NAME
        run: echo BRANCH_NAME=${GITHUB_REF##*/}

      - name: SONAR_PROJECT_KEY
        run: echo SONAR_PROJECT_KEY=${BRANCH_NAME}
          
        # mvn sonar:sonar -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.projectName="${SONAR_PROJECT_NAME}" -Dsonar.host.url=http://31.220.85.178:9001 -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.analysis.author=${{ github.actor }}
          
        # run: mvn sonar:sonar -Dsonar.projectKey=a1 -Dsonar.host.url=http://31.220.85.178:9001 -Dsonar.login=$SONAR_TOKEN -Dsonar.analysis.author=${{ github.actor }}
        
        # run: mvn sonar:sonar -Dsonar.projectKey=a1 -Dsonar.host.url=http://31.220.85.178:9001 -Dsonar.token=$SONAR_TOKEN
        # run: mvn sonar:sonar -Dsonar.projectKey=a1 -Dsonar.host.url=http://31.220.85.178:9001 -Dsonar.login=$SONAR_TOKEN -Dsonar.analysis.author=${GITHUB_ACTOR}
        # run: mvn sonar:sonar -Dsonar.projectKey=a1 -Dsonar.host.url=http://31.220.85.178:9001 -Dsonar.login=$SONAR_TOKEN -Dsonar.analysis.buildNumber=${GITHUB_RUN_ID} -Dsonar.analysis.pipeline=${GITHUB_WORKFLOW} -Dsonar.analysis.sha1=${GITHUB_SHA} -Dsonar.analysis.repository=${GITHUB_REPOSITORY} -Dsonar.analysis.branch=${GITHUB_REF} -Dsonar.analysis.author=${GITHUB_ACTOR}
        # The problem it's caused by /d:sonar.source="Project" or /d:sonar.tests="Project.Tests", just remove and works.
        # run: mvn sonar:sonar -Dsonar.projectKey=a1 -Dsonar.sources=. -Dsonar.host.url=http://31.220.85.178:9001 -Dsonar.token=$SONAR_TOKEN
        # run: mvn sonar:sonar -Dsonar.projectKey=a1 -Dsonar.sources=. -Dsonar.host.url=http://31.220.85.178:9001 -Dsonar.login=$SONAR_TOKEN
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_GLOBAL }}
          # GIT_ACTOR: ${{ github.actor }}

      # - name: Extract branch name
      #   shell: bash
      #   run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      #   id: extract_branch
